/*	$OpenBSD$	*/

/*
 * System call stubs for cbmc.
 *
 * DO NOT EDIT-- this file is automatically generated.
 * created from;	OpenBSD: syscalls.master,v 1.176 2017/04/28 13:50:55 mpi Exp 
 */

#include <sys/types.h>
#include <sys/mount.h>
#include <sys/socket.h>
#include <sys/signal.h>
#include <sys/syscallargs.h>

int
cbmc_exit()
{
	struct sys_exit_args v;
	struct proc *p = NULL;
	register_t r;
	return sys_exit(p, &v, r);
}

int
cbmc_read()
{
	struct sys_read_args v;
	struct proc *p = NULL;
	register_t r;
	return sys_read(p, &v, r);
}

int
cbmc_write()
{
	struct sys_write_args v;
	struct proc *p = NULL;
	register_t r;
	return sys_write(p, &v, r);
}

int
cbmc_open()
{
	struct sys_open_args v;
	struct proc *p = NULL;
	register_t r;
	return sys_open(p, &v, r);
}

int
cbmc_close()
{
	struct sys_close_args v;
	struct proc *p = NULL;
	register_t r;
	return sys_close(p, &v, r);
}

int
cbmc_getentropy()
{
	struct sys_getentropy_args v;
	struct proc *p = NULL;
	register_t r;
	return sys_getentropy(p, &v, r);
}

int
cbmc___tfork()
{
	struct sys___tfork_args v;
	struct proc *p = NULL;
	register_t r;
	return sys___tfork(p, &v, r);
}

int
cbmc_link()
{
	struct sys_link_args v;
	struct proc *p = NULL;
	register_t r;
	return sys_link(p, &v, r);
}

int
cbmc_unlink()
{
	struct sys_unlink_args v;
	struct proc *p = NULL;
	register_t r;
	return sys_unlink(p, &v, r);
}

int
cbmc_wait4()
{
	struct sys_wait4_args v;
	struct proc *p = NULL;
	register_t r;
	return sys_wait4(p, &v, r);
}

int
cbmc_chdir()
{
	struct sys_chdir_args v;
	struct proc *p = NULL;
	register_t r;
	return sys_chdir(p, &v, r);
}

int
cbmc_fchdir()
{
	struct sys_fchdir_args v;
	struct proc *p = NULL;
	register_t r;
	return sys_fchdir(p, &v, r);
}

int
cbmc_mknod()
{
	struct sys_mknod_args v;
	struct proc *p = NULL;
	register_t r;
	return sys_mknod(p, &v, r);
}

int
cbmc_chmod()
{
	struct sys_chmod_args v;
	struct proc *p = NULL;
	register_t r;
	return sys_chmod(p, &v, r);
}

int
cbmc_chown()
{
	struct sys_chown_args v;
	struct proc *p = NULL;
	register_t r;
	return sys_chown(p, &v, r);
}

int
cbmc_break()
{
	struct sys_obreak_args v;
	struct proc *p = NULL;
	register_t r;
	return sys_obreak(p, &v, r);
}

int
cbmc_getrusage()
{
	struct sys_getrusage_args v;
	struct proc *p = NULL;
	register_t r;
	return sys_getrusage(p, &v, r);
}

int
cbmc_mount()
{
	struct sys_mount_args v;
	struct proc *p = NULL;
	register_t r;
	return sys_mount(p, &v, r);
}

int
cbmc_unmount()
{
	struct sys_unmount_args v;
	struct proc *p = NULL;
	register_t r;
	return sys_unmount(p, &v, r);
}

int
cbmc_setuid()
{
	struct sys_setuid_args v;
	struct proc *p = NULL;
	register_t r;
	return sys_setuid(p, &v, r);
}

int
cbmc_ptrace()
{
	struct sys_ptrace_args v;
	struct proc *p = NULL;
	register_t r;
	return sys_ptrace(p, &v, r);
}

int
cbmc_recvmsg()
{
	struct sys_recvmsg_args v;
	struct proc *p = NULL;
	register_t r;
	return sys_recvmsg(p, &v, r);
}

int
cbmc_sendmsg()
{
	struct sys_sendmsg_args v;
	struct proc *p = NULL;
	register_t r;
	return sys_sendmsg(p, &v, r);
}

int
cbmc_recvfrom()
{
	struct sys_recvfrom_args v;
	struct proc *p = NULL;
	register_t r;
	return sys_recvfrom(p, &v, r);
}

int
cbmc_accept()
{
	struct sys_accept_args v;
	struct proc *p = NULL;
	register_t r;
	return sys_accept(p, &v, r);
}

int
cbmc_getpeername()
{
	struct sys_getpeername_args v;
	struct proc *p = NULL;
	register_t r;
	return sys_getpeername(p, &v, r);
}

int
cbmc_getsockname()
{
	struct sys_getsockname_args v;
	struct proc *p = NULL;
	register_t r;
	return sys_getsockname(p, &v, r);
}

int
cbmc_access()
{
	struct sys_access_args v;
	struct proc *p = NULL;
	register_t r;
	return sys_access(p, &v, r);
}

int
cbmc_chflags()
{
	struct sys_chflags_args v;
	struct proc *p = NULL;
	register_t r;
	return sys_chflags(p, &v, r);
}

int
cbmc_fchflags()
{
	struct sys_fchflags_args v;
	struct proc *p = NULL;
	register_t r;
	return sys_fchflags(p, &v, r);
}

int
cbmc_stat()
{
	struct sys_stat_args v;
	struct proc *p = NULL;
	register_t r;
	return sys_stat(p, &v, r);
}

int
cbmc_lstat()
{
	struct sys_lstat_args v;
	struct proc *p = NULL;
	register_t r;
	return sys_lstat(p, &v, r);
}

int
cbmc_dup()
{
	struct sys_dup_args v;
	struct proc *p = NULL;
	register_t r;
	return sys_dup(p, &v, r);
}

int
cbmc_fstatat()
{
	struct sys_fstatat_args v;
	struct proc *p = NULL;
	register_t r;
	return sys_fstatat(p, &v, r);
}

int
cbmc_profil()
{
	struct sys_profil_args v;
	struct proc *p = NULL;
	register_t r;
	return sys_profil(p, &v, r);
}

int
cbmc_ktrace()
{
	struct sys_ktrace_args v;
	struct proc *p = NULL;
	register_t r;
	return sys_ktrace(p, &v, r);
}

int
cbmc_sigaction()
{
	struct sys_sigaction_args v;
	struct proc *p = NULL;
	register_t r;
	return sys_sigaction(p, &v, r);
}

int
cbmc_sigprocmask()
{
	struct sys_sigprocmask_args v;
	struct proc *p = NULL;
	register_t r;
	return sys_sigprocmask(p, &v, r);
}

int
cbmc_setlogin()
{
	struct sys_setlogin_args v;
	struct proc *p = NULL;
	register_t r;
	return sys_setlogin(p, &v, r);
}

int
cbmc_acct()
{
	struct sys_acct_args v;
	struct proc *p = NULL;
	register_t r;
	return sys_acct(p, &v, r);
}

int
cbmc_fstat()
{
	struct sys_fstat_args v;
	struct proc *p = NULL;
	register_t r;
	return sys_fstat(p, &v, r);
}

int
cbmc_ioctl()
{
	struct sys_ioctl_args v;
	struct proc *p = NULL;
	register_t r;
	return sys_ioctl(p, &v, r);
}

int
cbmc_reboot()
{
	struct sys_reboot_args v;
	struct proc *p = NULL;
	register_t r;
	return sys_reboot(p, &v, r);
}

int
cbmc_revoke()
{
	struct sys_revoke_args v;
	struct proc *p = NULL;
	register_t r;
	return sys_revoke(p, &v, r);
}

int
cbmc_symlink()
{
	struct sys_symlink_args v;
	struct proc *p = NULL;
	register_t r;
	return sys_symlink(p, &v, r);
}

int
cbmc_readlink()
{
	struct sys_readlink_args v;
	struct proc *p = NULL;
	register_t r;
	return sys_readlink(p, &v, r);
}

int
cbmc_execve()
{
	struct sys_execve_args v;
	struct proc *p = NULL;
	register_t r;
	return sys_execve(p, &v, r);
}

int
cbmc_umask()
{
	struct sys_umask_args v;
	struct proc *p = NULL;
	register_t r;
	return sys_umask(p, &v, r);
}

int
cbmc_chroot()
{
	struct sys_chroot_args v;
	struct proc *p = NULL;
	register_t r;
	return sys_chroot(p, &v, r);
}

int
cbmc_getfsstat()
{
	struct sys_getfsstat_args v;
	struct proc *p = NULL;
	register_t r;
	return sys_getfsstat(p, &v, r);
}

int
cbmc_statfs()
{
	struct sys_statfs_args v;
	struct proc *p = NULL;
	register_t r;
	return sys_statfs(p, &v, r);
}

int
cbmc_fstatfs()
{
	struct sys_fstatfs_args v;
	struct proc *p = NULL;
	register_t r;
	return sys_fstatfs(p, &v, r);
}

int
cbmc_fhstatfs()
{
	struct sys_fhstatfs_args v;
	struct proc *p = NULL;
	register_t r;
	return sys_fhstatfs(p, &v, r);
}

int
cbmc_gettimeofday()
{
	struct sys_gettimeofday_args v;
	struct proc *p = NULL;
	register_t r;
	return sys_gettimeofday(p, &v, r);
}

int
cbmc_settimeofday()
{
	struct sys_settimeofday_args v;
	struct proc *p = NULL;
	register_t r;
	return sys_settimeofday(p, &v, r);
}

int
cbmc_setitimer()
{
	struct sys_setitimer_args v;
	struct proc *p = NULL;
	register_t r;
	return sys_setitimer(p, &v, r);
}

int
cbmc_getitimer()
{
	struct sys_getitimer_args v;
	struct proc *p = NULL;
	register_t r;
	return sys_getitimer(p, &v, r);
}

int
cbmc_select()
{
	struct sys_select_args v;
	struct proc *p = NULL;
	register_t r;
	return sys_select(p, &v, r);
}

int
cbmc_kevent()
{
	struct sys_kevent_args v;
	struct proc *p = NULL;
	register_t r;
	return sys_kevent(p, &v, r);
}

int
cbmc_munmap()
{
	struct sys_munmap_args v;
	struct proc *p = NULL;
	register_t r;
	return sys_munmap(p, &v, r);
}

int
cbmc_mprotect()
{
	struct sys_mprotect_args v;
	struct proc *p = NULL;
	register_t r;
	return sys_mprotect(p, &v, r);
}

int
cbmc_madvise()
{
	struct sys_madvise_args v;
	struct proc *p = NULL;
	register_t r;
	return sys_madvise(p, &v, r);
}

int
cbmc_utimes()
{
	struct sys_utimes_args v;
	struct proc *p = NULL;
	register_t r;
	return sys_utimes(p, &v, r);
}

int
cbmc_futimes()
{
	struct sys_futimes_args v;
	struct proc *p = NULL;
	register_t r;
	return sys_futimes(p, &v, r);
}

int
cbmc_mincore()
{
	struct sys_mincore_args v;
	struct proc *p = NULL;
	register_t r;
	return sys_mincore(p, &v, r);
}

int
cbmc_getgroups()
{
	struct sys_getgroups_args v;
	struct proc *p = NULL;
	register_t r;
	return sys_getgroups(p, &v, r);
}

int
cbmc_setgroups()
{
	struct sys_setgroups_args v;
	struct proc *p = NULL;
	register_t r;
	return sys_setgroups(p, &v, r);
}

int
cbmc_setpgid()
{
	struct sys_setpgid_args v;
	struct proc *p = NULL;
	register_t r;
	return sys_setpgid(p, &v, r);
}

int
cbmc_futex()
{
	struct sys_futex_args v;
	struct proc *p = NULL;
	register_t r;
	return sys_futex(p, &v, r);
}

int
cbmc_utimensat()
{
	struct sys_utimensat_args v;
	struct proc *p = NULL;
	register_t r;
	return sys_utimensat(p, &v, r);
}

int
cbmc_futimens()
{
	struct sys_futimens_args v;
	struct proc *p = NULL;
	register_t r;
	return sys_futimens(p, &v, r);
}

int
cbmc_kbind()
{
	struct sys_kbind_args v;
	struct proc *p = NULL;
	register_t r;
	return sys_kbind(p, &v, r);
}

int
cbmc_clock_gettime()
{
	struct sys_clock_gettime_args v;
	struct proc *p = NULL;
	register_t r;
	return sys_clock_gettime(p, &v, r);
}

int
cbmc_clock_settime()
{
	struct sys_clock_settime_args v;
	struct proc *p = NULL;
	register_t r;
	return sys_clock_settime(p, &v, r);
}

int
cbmc_clock_getres()
{
	struct sys_clock_getres_args v;
	struct proc *p = NULL;
	register_t r;
	return sys_clock_getres(p, &v, r);
}

int
cbmc_dup2()
{
	struct sys_dup2_args v;
	struct proc *p = NULL;
	register_t r;
	return sys_dup2(p, &v, r);
}

int
cbmc_nanosleep()
{
	struct sys_nanosleep_args v;
	struct proc *p = NULL;
	register_t r;
	return sys_nanosleep(p, &v, r);
}

int
cbmc_fcntl()
{
	struct sys_fcntl_args v;
	struct proc *p = NULL;
	register_t r;
	return sys_fcntl(p, &v, r);
}

int
cbmc_accept4()
{
	struct sys_accept4_args v;
	struct proc *p = NULL;
	register_t r;
	return sys_accept4(p, &v, r);
}

int
cbmc___thrsleep()
{
	struct sys___thrsleep_args v;
	struct proc *p = NULL;
	register_t r;
	return sys___thrsleep(p, &v, r);
}

int
cbmc_fsync()
{
	struct sys_fsync_args v;
	struct proc *p = NULL;
	register_t r;
	return sys_fsync(p, &v, r);
}

int
cbmc_setpriority()
{
	struct sys_setpriority_args v;
	struct proc *p = NULL;
	register_t r;
	return sys_setpriority(p, &v, r);
}

int
cbmc_socket()
{
	struct sys_socket_args v;
	struct proc *p = NULL;
	register_t r;
	return sys_socket(p, &v, r);
}

int
cbmc_connect()
{
	struct sys_connect_args v;
	struct proc *p = NULL;
	register_t r;
	return sys_connect(p, &v, r);
}

int
cbmc_getdents()
{
	struct sys_getdents_args v;
	struct proc *p = NULL;
	register_t r;
	return sys_getdents(p, &v, r);
}

int
cbmc_getpriority()
{
	struct sys_getpriority_args v;
	struct proc *p = NULL;
	register_t r;
	return sys_getpriority(p, &v, r);
}

int
cbmc_pipe2()
{
	struct sys_pipe2_args v;
	struct proc *p = NULL;
	register_t r;
	return sys_pipe2(p, &v, r);
}

int
cbmc_dup3()
{
	struct sys_dup3_args v;
	struct proc *p = NULL;
	register_t r;
	return sys_dup3(p, &v, r);
}

int
cbmc_sigreturn()
{
	struct sys_sigreturn_args v;
	struct proc *p = NULL;
	register_t r;
	return sys_sigreturn(p, &v, r);
}

int
cbmc_bind()
{
	struct sys_bind_args v;
	struct proc *p = NULL;
	register_t r;
	return sys_bind(p, &v, r);
}

int
cbmc_setsockopt()
{
	struct sys_setsockopt_args v;
	struct proc *p = NULL;
	register_t r;
	return sys_setsockopt(p, &v, r);
}

int
cbmc_listen()
{
	struct sys_listen_args v;
	struct proc *p = NULL;
	register_t r;
	return sys_listen(p, &v, r);
}

int
cbmc_chflagsat()
{
	struct sys_chflagsat_args v;
	struct proc *p = NULL;
	register_t r;
	return sys_chflagsat(p, &v, r);
}

int
cbmc_pledge()
{
	struct sys_pledge_args v;
	struct proc *p = NULL;
	register_t r;
	return sys_pledge(p, &v, r);
}

int
cbmc_ppoll()
{
	struct sys_ppoll_args v;
	struct proc *p = NULL;
	register_t r;
	return sys_ppoll(p, &v, r);
}

int
cbmc_pselect()
{
	struct sys_pselect_args v;
	struct proc *p = NULL;
	register_t r;
	return sys_pselect(p, &v, r);
}

int
cbmc_sigsuspend()
{
	struct sys_sigsuspend_args v;
	struct proc *p = NULL;
	register_t r;
	return sys_sigsuspend(p, &v, r);
}

int
cbmc_sendsyslog()
{
	struct sys_sendsyslog_args v;
	struct proc *p = NULL;
	register_t r;
	return sys_sendsyslog(p, &v, r);
}

int
cbmc_getsockopt()
{
	struct sys_getsockopt_args v;
	struct proc *p = NULL;
	register_t r;
	return sys_getsockopt(p, &v, r);
}

int
cbmc_thrkill()
{
	struct sys_thrkill_args v;
	struct proc *p = NULL;
	register_t r;
	return sys_thrkill(p, &v, r);
}

int
cbmc_readv()
{
	struct sys_readv_args v;
	struct proc *p = NULL;
	register_t r;
	return sys_readv(p, &v, r);
}

int
cbmc_writev()
{
	struct sys_writev_args v;
	struct proc *p = NULL;
	register_t r;
	return sys_writev(p, &v, r);
}

int
cbmc_kill()
{
	struct sys_kill_args v;
	struct proc *p = NULL;
	register_t r;
	return sys_kill(p, &v, r);
}

int
cbmc_fchown()
{
	struct sys_fchown_args v;
	struct proc *p = NULL;
	register_t r;
	return sys_fchown(p, &v, r);
}

int
cbmc_fchmod()
{
	struct sys_fchmod_args v;
	struct proc *p = NULL;
	register_t r;
	return sys_fchmod(p, &v, r);
}

int
cbmc_setreuid()
{
	struct sys_setreuid_args v;
	struct proc *p = NULL;
	register_t r;
	return sys_setreuid(p, &v, r);
}

int
cbmc_setregid()
{
	struct sys_setregid_args v;
	struct proc *p = NULL;
	register_t r;
	return sys_setregid(p, &v, r);
}

int
cbmc_rename()
{
	struct sys_rename_args v;
	struct proc *p = NULL;
	register_t r;
	return sys_rename(p, &v, r);
}

int
cbmc_flock()
{
	struct sys_flock_args v;
	struct proc *p = NULL;
	register_t r;
	return sys_flock(p, &v, r);
}

int
cbmc_mkfifo()
{
	struct sys_mkfifo_args v;
	struct proc *p = NULL;
	register_t r;
	return sys_mkfifo(p, &v, r);
}

int
cbmc_sendto()
{
	struct sys_sendto_args v;
	struct proc *p = NULL;
	register_t r;
	return sys_sendto(p, &v, r);
}

int
cbmc_shutdown()
{
	struct sys_shutdown_args v;
	struct proc *p = NULL;
	register_t r;
	return sys_shutdown(p, &v, r);
}

int
cbmc_socketpair()
{
	struct sys_socketpair_args v;
	struct proc *p = NULL;
	register_t r;
	return sys_socketpair(p, &v, r);
}

int
cbmc_mkdir()
{
	struct sys_mkdir_args v;
	struct proc *p = NULL;
	register_t r;
	return sys_mkdir(p, &v, r);
}

int
cbmc_rmdir()
{
	struct sys_rmdir_args v;
	struct proc *p = NULL;
	register_t r;
	return sys_rmdir(p, &v, r);
}

int
cbmc_adjtime()
{
	struct sys_adjtime_args v;
	struct proc *p = NULL;
	register_t r;
	return sys_adjtime(p, &v, r);
}

int
cbmc_getlogin_r()
{
	struct sys_getlogin_r_args v;
	struct proc *p = NULL;
	register_t r;
	return sys_getlogin_r(p, &v, r);
}

int
cbmc_quotactl()
{
	struct sys_quotactl_args v;
	struct proc *p = NULL;
	register_t r;
	return sys_quotactl(p, &v, r);
}

int
cbmc_nfssvc()
{
	struct sys_nfssvc_args v;
	struct proc *p = NULL;
	register_t r;
	return sys_nfssvc(p, &v, r);
}

int
cbmc_getfh()
{
	struct sys_getfh_args v;
	struct proc *p = NULL;
	register_t r;
	return sys_getfh(p, &v, r);
}

int
cbmc_sysarch()
{
	struct sys_sysarch_args v;
	struct proc *p = NULL;
	register_t r;
	return sys_sysarch(p, &v, r);
}

int
cbmc_pread()
{
	struct sys_pread_args v;
	struct proc *p = NULL;
	register_t r;
	return sys_pread(p, &v, r);
}

int
cbmc_pwrite()
{
	struct sys_pwrite_args v;
	struct proc *p = NULL;
	register_t r;
	return sys_pwrite(p, &v, r);
}

int
cbmc_setgid()
{
	struct sys_setgid_args v;
	struct proc *p = NULL;
	register_t r;
	return sys_setgid(p, &v, r);
}

int
cbmc_setegid()
{
	struct sys_setegid_args v;
	struct proc *p = NULL;
	register_t r;
	return sys_setegid(p, &v, r);
}

int
cbmc_seteuid()
{
	struct sys_seteuid_args v;
	struct proc *p = NULL;
	register_t r;
	return sys_seteuid(p, &v, r);
}

int
cbmc_pathconf()
{
	struct sys_pathconf_args v;
	struct proc *p = NULL;
	register_t r;
	return sys_pathconf(p, &v, r);
}

int
cbmc_fpathconf()
{
	struct sys_fpathconf_args v;
	struct proc *p = NULL;
	register_t r;
	return sys_fpathconf(p, &v, r);
}

int
cbmc_swapctl()
{
	struct sys_swapctl_args v;
	struct proc *p = NULL;
	register_t r;
	return sys_swapctl(p, &v, r);
}

int
cbmc_getrlimit()
{
	struct sys_getrlimit_args v;
	struct proc *p = NULL;
	register_t r;
	return sys_getrlimit(p, &v, r);
}

int
cbmc_setrlimit()
{
	struct sys_setrlimit_args v;
	struct proc *p = NULL;
	register_t r;
	return sys_setrlimit(p, &v, r);
}

int
cbmc_mmap()
{
	struct sys_mmap_args v;
	struct proc *p = NULL;
	register_t r;
	return sys_mmap(p, &v, r);
}

int
cbmc_lseek()
{
	struct sys_lseek_args v;
	struct proc *p = NULL;
	register_t r;
	return sys_lseek(p, &v, r);
}

int
cbmc_truncate()
{
	struct sys_truncate_args v;
	struct proc *p = NULL;
	register_t r;
	return sys_truncate(p, &v, r);
}

int
cbmc_ftruncate()
{
	struct sys_ftruncate_args v;
	struct proc *p = NULL;
	register_t r;
	return sys_ftruncate(p, &v, r);
}

int
cbmc_sysctl()
{
	struct sys_sysctl_args v;
	struct proc *p = NULL;
	register_t r;
	return sys_sysctl(p, &v, r);
}

int
cbmc_mlock()
{
	struct sys_mlock_args v;
	struct proc *p = NULL;
	register_t r;
	return sys_mlock(p, &v, r);
}

int
cbmc_munlock()
{
	struct sys_munlock_args v;
	struct proc *p = NULL;
	register_t r;
	return sys_munlock(p, &v, r);
}

int
cbmc_getpgid()
{
	struct sys_getpgid_args v;
	struct proc *p = NULL;
	register_t r;
	return sys_getpgid(p, &v, r);
}

int
cbmc_utrace()
{
	struct sys_utrace_args v;
	struct proc *p = NULL;
	register_t r;
	return sys_utrace(p, &v, r);
}

int
cbmc_semget()
{
	struct sys_semget_args v;
	struct proc *p = NULL;
	register_t r;
	return sys_semget(p, &v, r);
}

int
cbmc_msgget()
{
	struct sys_msgget_args v;
	struct proc *p = NULL;
	register_t r;
	return sys_msgget(p, &v, r);
}

int
cbmc_msgsnd()
{
	struct sys_msgsnd_args v;
	struct proc *p = NULL;
	register_t r;
	return sys_msgsnd(p, &v, r);
}

int
cbmc_msgrcv()
{
	struct sys_msgrcv_args v;
	struct proc *p = NULL;
	register_t r;
	return sys_msgrcv(p, &v, r);
}

int
cbmc_shmat()
{
	struct sys_shmat_args v;
	struct proc *p = NULL;
	register_t r;
	return sys_shmat(p, &v, r);
}

int
cbmc_shmdt()
{
	struct sys_shmdt_args v;
	struct proc *p = NULL;
	register_t r;
	return sys_shmdt(p, &v, r);
}

int
cbmc_minherit()
{
	struct sys_minherit_args v;
	struct proc *p = NULL;
	register_t r;
	return sys_minherit(p, &v, r);
}

int
cbmc_poll()
{
	struct sys_poll_args v;
	struct proc *p = NULL;
	register_t r;
	return sys_poll(p, &v, r);
}

int
cbmc_lchown()
{
	struct sys_lchown_args v;
	struct proc *p = NULL;
	register_t r;
	return sys_lchown(p, &v, r);
}

int
cbmc_getsid()
{
	struct sys_getsid_args v;
	struct proc *p = NULL;
	register_t r;
	return sys_getsid(p, &v, r);
}

int
cbmc_msync()
{
	struct sys_msync_args v;
	struct proc *p = NULL;
	register_t r;
	return sys_msync(p, &v, r);
}

int
cbmc_pipe()
{
	struct sys_pipe_args v;
	struct proc *p = NULL;
	register_t r;
	return sys_pipe(p, &v, r);
}

int
cbmc_fhopen()
{
	struct sys_fhopen_args v;
	struct proc *p = NULL;
	register_t r;
	return sys_fhopen(p, &v, r);
}

int
cbmc_preadv()
{
	struct sys_preadv_args v;
	struct proc *p = NULL;
	register_t r;
	return sys_preadv(p, &v, r);
}

int
cbmc_pwritev()
{
	struct sys_pwritev_args v;
	struct proc *p = NULL;
	register_t r;
	return sys_pwritev(p, &v, r);
}

int
cbmc_mlockall()
{
	struct sys_mlockall_args v;
	struct proc *p = NULL;
	register_t r;
	return sys_mlockall(p, &v, r);
}

int
cbmc_getresuid()
{
	struct sys_getresuid_args v;
	struct proc *p = NULL;
	register_t r;
	return sys_getresuid(p, &v, r);
}

int
cbmc_setresuid()
{
	struct sys_setresuid_args v;
	struct proc *p = NULL;
	register_t r;
	return sys_setresuid(p, &v, r);
}

int
cbmc_getresgid()
{
	struct sys_getresgid_args v;
	struct proc *p = NULL;
	register_t r;
	return sys_getresgid(p, &v, r);
}

int
cbmc_setresgid()
{
	struct sys_setresgid_args v;
	struct proc *p = NULL;
	register_t r;
	return sys_setresgid(p, &v, r);
}

int
cbmc_mquery()
{
	struct sys_mquery_args v;
	struct proc *p = NULL;
	register_t r;
	return sys_mquery(p, &v, r);
}

int
cbmc_closefrom()
{
	struct sys_closefrom_args v;
	struct proc *p = NULL;
	register_t r;
	return sys_closefrom(p, &v, r);
}

int
cbmc_sigaltstack()
{
	struct sys_sigaltstack_args v;
	struct proc *p = NULL;
	register_t r;
	return sys_sigaltstack(p, &v, r);
}

int
cbmc_shmget()
{
	struct sys_shmget_args v;
	struct proc *p = NULL;
	register_t r;
	return sys_shmget(p, &v, r);
}

int
cbmc_semop()
{
	struct sys_semop_args v;
	struct proc *p = NULL;
	register_t r;
	return sys_semop(p, &v, r);
}

int
cbmc_fhstat()
{
	struct sys_fhstat_args v;
	struct proc *p = NULL;
	register_t r;
	return sys_fhstat(p, &v, r);
}

int
cbmc___semctl()
{
	struct sys___semctl_args v;
	struct proc *p = NULL;
	register_t r;
	return sys___semctl(p, &v, r);
}

int
cbmc_shmctl()
{
	struct sys_shmctl_args v;
	struct proc *p = NULL;
	register_t r;
	return sys_shmctl(p, &v, r);
}

int
cbmc_msgctl()
{
	struct sys_msgctl_args v;
	struct proc *p = NULL;
	register_t r;
	return sys_msgctl(p, &v, r);
}

int
cbmc___thrwakeup()
{
	struct sys___thrwakeup_args v;
	struct proc *p = NULL;
	register_t r;
	return sys___thrwakeup(p, &v, r);
}

int
cbmc___threxit()
{
	struct sys___threxit_args v;
	struct proc *p = NULL;
	register_t r;
	return sys___threxit(p, &v, r);
}

int
cbmc___thrsigdivert()
{
	struct sys___thrsigdivert_args v;
	struct proc *p = NULL;
	register_t r;
	return sys___thrsigdivert(p, &v, r);
}

int
cbmc___getcwd()
{
	struct sys___getcwd_args v;
	struct proc *p = NULL;
	register_t r;
	return sys___getcwd(p, &v, r);
}

int
cbmc_adjfreq()
{
	struct sys_adjfreq_args v;
	struct proc *p = NULL;
	register_t r;
	return sys_adjfreq(p, &v, r);
}

int
cbmc_setrtable()
{
	struct sys_setrtable_args v;
	struct proc *p = NULL;
	register_t r;
	return sys_setrtable(p, &v, r);
}

int
cbmc_faccessat()
{
	struct sys_faccessat_args v;
	struct proc *p = NULL;
	register_t r;
	return sys_faccessat(p, &v, r);
}

int
cbmc_fchmodat()
{
	struct sys_fchmodat_args v;
	struct proc *p = NULL;
	register_t r;
	return sys_fchmodat(p, &v, r);
}

int
cbmc_fchownat()
{
	struct sys_fchownat_args v;
	struct proc *p = NULL;
	register_t r;
	return sys_fchownat(p, &v, r);
}

int
cbmc_linkat()
{
	struct sys_linkat_args v;
	struct proc *p = NULL;
	register_t r;
	return sys_linkat(p, &v, r);
}

int
cbmc_mkdirat()
{
	struct sys_mkdirat_args v;
	struct proc *p = NULL;
	register_t r;
	return sys_mkdirat(p, &v, r);
}

int
cbmc_mkfifoat()
{
	struct sys_mkfifoat_args v;
	struct proc *p = NULL;
	register_t r;
	return sys_mkfifoat(p, &v, r);
}

int
cbmc_mknodat()
{
	struct sys_mknodat_args v;
	struct proc *p = NULL;
	register_t r;
	return sys_mknodat(p, &v, r);
}

int
cbmc_openat()
{
	struct sys_openat_args v;
	struct proc *p = NULL;
	register_t r;
	return sys_openat(p, &v, r);
}

int
cbmc_readlinkat()
{
	struct sys_readlinkat_args v;
	struct proc *p = NULL;
	register_t r;
	return sys_readlinkat(p, &v, r);
}

int
cbmc_renameat()
{
	struct sys_renameat_args v;
	struct proc *p = NULL;
	register_t r;
	return sys_renameat(p, &v, r);
}

int
cbmc_symlinkat()
{
	struct sys_symlinkat_args v;
	struct proc *p = NULL;
	register_t r;
	return sys_symlinkat(p, &v, r);
}

int
cbmc_unlinkat()
{
	struct sys_unlinkat_args v;
	struct proc *p = NULL;
	register_t r;
	return sys_unlinkat(p, &v, r);
}

int
cbmc___set_tcb()
{
	struct sys___set_tcb_args v;
	struct proc *p = NULL;
	register_t r;
	return sys___set_tcb(p, &v, r);
}
